---
- hosts: all
  become: yes
  tasks:
    - name: Generate a random string
      ansible.builtin.shell: tr -dc a-z0-9 < /dev/urandom | head -c 10
      register: random_hostname
    - name: rename host
      ansible.builtin.hostname:
        name: "{{ random_hostname.stdout }}"
    - name: Update apt cache and install packages
      apt:
        pkg:
        - containerd
        update_cache: yes
    - name: Make sure containerd is running
      ansible.builtin.systemd:
        name: containerd
        enabled: yes
        state: started